export { TabbedCarousel } from './Carousel';
export { FlipCardToTarget } from './FlipCardToTarget';

export { renderContentModule } from './ContentModules';

export { PaletteSwitcher, PALETTES, getInitialPalette } from './PaletteSwitcher';
export type { Palette } from './PaletteSwitcher';

export type {
  LearningRate,
  RateConfig,
  WordStats,
  WordsSeenStore,
  ExerciseEvent,
  WordReadiness,
  MetricsSummary,
  CardType,
  SessionSnapshot,
  ExerciseData,
  ActiveLevel,
  WordTheme,
  StreakData,
} from './Session';
export {
  RATE_CONFIG,
  readActiveLevel,
  writeActiveLevel,
  readLevelSelected,
  writeLevelSelected,
  migrateStorage,
  readWordsSeen,
  writeWordsSeen,
  updateWordStats,
  seedWordStats,
  readLearningRate,
  writeLearningRate,
  appendExerciseEvent,
  readExerciseLog,
  computeWordMetrics,
  getMetricsSummary,
  readSessionTimeout,
  writeSessionTimeout,
  readStorageUsage,
  readKnownWords,
  addKnownWord,
  removeKnownWord,
  readKnownWordConfirmed,
  writeKnownWordConfirmed,
  readFlipAnimation,
  writeFlipAnimation,
  healWordsSeen,
  readActiveTheme,
  writeActiveTheme,
  readHardcoreMode,
  writeHardcoreMode,
  readStreak,
  recordSessionForStreak,
  hasSessionToday,
  pickNextCard,
  generateExerciseData,
  generateExerciseDataSafe,
  hasSeenCoachMark,
  markCoachMarkSeen,
  useCoachMark,
} from './Session';
